apiVersion: v2
name: shield
description: Helm Chart for shield
type: application
version: 0.2.1
appVersion: 0.2.1
home: https://github.com/300481/shield
description: shield makes the underlying host "magically" disappear during network attacks.
keywords:
  - iptables
  - firewall
  - container
  - security
sources:
  - https://github.com/300481/shield
maintainers:
  - name: "300481"
engine: gotpl
kubeVersion: ">=1.16.0-0"
annotations:
  artifacthub.io/images: |
    - name: shield
      image: 300481/shield:0.2.1
  artifacthub.io/maintainers: |
    - name: 300481
      email: 300481@300481.de